# ?? ??
server:
  port: 80  # ??????? ??? ?? ??

# Spring ?????? ??
spring:
  application:
    name: gateway  # ??????? ?? ??

  # Spring Cloud Gateway ??
  cloud:
    gateway:
      mvc:
        routes: # ??? ?? ??아
          - id: accountRoute  # ??? ID
            uri: lb://ACCOUNT # ??? ??? URI (??? ?? URI? ???? ?)
            predicates: # ??? ????? ??
              - Path=/api/accounts/**  # /account/** ??? ?? ??? ??

          - id: chatbotRoute
            uri: lb://CHATBOT
            predicates:
              - Path=/api/chatbot/**

          - id: notificationRoute
            uri: lb://NOTIFICATION
            predicates:
              - Path=/api/notification/**

          - id: paymentRoute
            uri: lb://PAYMENT
            predicates:
              - Path=/api/payments/**

          - id: travelRoute
            uri: lb://TRAVEL
            predicates:
              - Path=/api/travel/**

          - id: userRoute
            uri: lb://USER
            predicates:
              - Path=/api/user/**
# Eureka ??
eureka:
  instance:
    prefer-ip-address: true  # ???? ?? ? IP ??? ??
  client:
    register-with-eureka: true  # Eureka ??? ?? ??
    fetch-registry: true  # Eureka ???? ??? ??? ??? ???? ??
    service-url:
      defaultZone: http://j11a604.p.ssafy.io:8761/eureka # Eureka ??? ?? URL (??? ?? URL? ???? ?)

# ?? ????? ??
management:
  endpoint:
    web:
      exposure:
        include: "*"  # ?? ?? ????? ??


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
