spring:
  application:
    name: eureka  # ??????? ??? 'eureka'? ?????.

server:
  port: 8761  # ??? ??? ?? ??? 8761? ?????.

eureka:
  client:
    register-with-eureka: false  # ? ??? Eureka ???? ????? ?? Eureka ??? ???? ??? ?????.
    fetch-registry: false  # ?? Eureka ????? ??? ?? ??? ???? ??? ?????.
    # false? ???? ??? ? ???? ??? ??? ???? ??? ?? ??? ????? ??? ????? ??? ??? ??
    service-url:
      defaultZone: http://j11a604.p.ssafy.io:8761/eureka # Eureka ??????? Eureka??? ????? ??, Eureka ??? URL? ???? ???.

  server:
    wait-time-in-ms-when-sync-empty: 5  # Eureka ??? ???? ?, ?????? ?? ?? ?? ?? ??? 5ms? ?????.

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ?? ?? ?????? ??? ????? ?????.
