spring:
  application:
    name: travel

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
          ssl:
            trust: "*"

server:
  port: 8085

# Eureka ??
eureka:
  instance:
    hostname: j11a604.p.ssafy.io
  client:
    register-with-eureka: true  # Eureka ??? ?? ??
    fetch-registry: true  # Eureka ???? ??? ??? ??? ???? ??
    service-url:
      defaultZone: http://j11a604.p.ssafy.io:8761/eureka # Eureka ??? ?? URL (??? ?? URL? ???? ?)

# ?? ????? ??
management:
  endpoint:
    web:
      exposure:
        include: "*"  # ?? ?? ????? ??


logging:
  level:
    org.springframework.cloud.gateway: DEBUG